{
 "title": "Health",
 "tags": [
  "services",
  "health"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Thinkcenter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node\", host=\"thinkcenter\"}"
    }
   ]
  },
  {
   "title": "Vpsfree",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node\", host=\"vpsfree\"}"
    }
   ]
  },
  {
   "title": "Prusa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node\", host=\"prusa\"}"
    }
   ]
  },
  {
   "title": "Rpi4",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node\", host=\"rpi4\"}"
    }
   ]
  },
  {
   "title": "Rak2245",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node\", host=\"rak2245\"}"
    }
   ]
  },
  { "title": "User Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Jellyfin",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"jellyfin.service\",state=\"active\",host=\"thinkcenter\"}"
    }
   ]
  },
  {
   "title": "Immich",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"immich-server.service\",state=\"active\",host=\"thinkcenter\"}"
    }
   ]
  },
  {
   "title": "Memos",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"memos.service\",state=\"active\",host=\"thinkcenter\"}"
    }
   ]
  },
  {
   "title": "Octoprint",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"octoprint\"}"
    }
   ]
  },
  {
   "title": "Vaultwarden",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"vaultwarden.service\",state=\"active\",host=\"thinkcenter\"}"
    }
   ]
  },
  { "title": "Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Grafana",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"grafana.service\",state=\"active\",host=\"thinkcenter\"}"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"prometheus.service\",state=\"active\",host=\"thinkcenter\"}"
    }
   ]
  },
  {
   "title": "Ntfy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"ntfy-sh.service\",state=\"active\",host=\"thinkcenter\"}"
    }
   ]
  },
  {
   "title": "Loki",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"loki.service\",state=\"active\",host=\"thinkcenter\"}"
    }
   ]
  },
  {
   "title": "Watchdog",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"watchdog\"}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Wireguard",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_carrier{device=\"wg0\",host=\"thinkcenter\"}"
    }
   ]
  },
  {
   "title": "NB Management",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"netbird-management.service\",state=\"active\",host=\"thinkcenter\"}"
    }
   ]
  },
  {
   "title": "NB Relay",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"netbird-relay.service\",state=\"active\",host=\"thinkcenter\"}"
    }
   ]
  },
  {
   "title": "NB Signal",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"netbird-signal.service\",state=\"active\",host=\"vpsfree\"}"
    }
   ]
  },
  {
   "title": "Concentratord",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"chirpstack-concentratord.service\",state=\"active\",host=\"rak2245\"}"
    }
   ]
  },
  {
   "title": "UDP Forwarder",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"chirpstack-udp-forwarder.service\",state=\"active\",host=\"rak2245\"}"
    }
   ]
  },
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Nginx",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"nginx.service\",state=\"active\",host=\"thinkcenter\"}"
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"postgresql.service\",state=\"active\",host=\"thinkcenter\"}"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"redis.service\",state=\"active\",host=\"thinkcenter\"}"
    }
   ]
  },
  {
   "title": "Acme",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(node_systemd_unit_state{name=\"acme-krejci.io.service\",state=\"active\"})"
    }
   ]
  },
  {
   "title": "Borg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - clamp_max(sum(node_systemd_unit_state{name=~\"borgbackup-job-.*\\\\.service\",state=\"failed\"} or vector(0)), 1)"
    }
   ]
  },
  {
   "title": "IPP-USB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"ipp-usb.service\",state=\"active\",host=\"thinkcenter\"}"
    }
   ]
  },
  { "title": "Backups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Immich Local",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - borg_backup_last_success_timestamp{name=\"immich\",target=\"local\"}) / 3600"
    }
   ]
  },
  {
   "title": "Immich Remote",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - borg_backup_last_success_timestamp{name=\"immich\",target=\"remote\"}) / 3600"
    }
   ]
  },
  {
   "title": "Memos Local",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - borg_backup_last_success_timestamp{name=\"memos\",target=\"local\"}) / 3600"
    }
   ]
  },
  {
   "title": "Memos Remote",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - borg_backup_last_success_timestamp{name=\"memos\",target=\"remote\"}) / 3600"
    }
   ]
  },
  {
   "title": "Vaultwarden Local",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - borg_backup_last_success_timestamp{name=\"vaultwarden\",target=\"local\"}) / 3600"
    }
   ]
  },
  {
   "title": "Vaultwarden Remote",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - borg_backup_last_success_timestamp{name=\"vaultwarden\",target=\"remote\"}) / 3600"
    }
   ]
  },
  { "title": "Immich", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "up{job=\"immich\"}",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Jellyfin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"jellyfin.service\",state=\"active\",host=\"thinkcenter\"}",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Memos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"memos.service\",state=\"active\",host=\"thinkcenter\"}",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Octoprint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "up{job=\"octoprint\"}",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Vaultwarden", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"vaultwarden.service\",state=\"active\",host=\"thinkcenter\"}",
     "legendFormat": " "
    }
   ]
  }
 ]
}