theme = "sonokai"

[editor]
mouse = false
shell = ["zsh", "-c"]
cursorline = true
idle-timeout = 5
true-color = true
bufferline = "always"
color-modes = true

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "none"
tab = "none"
newline = "all"

[editor.indent-guides]
render = true

[keys.normal]
p = "paste_clipboard_after"
P = "paste_clipboard_before"
y = "yank_joined_to_clipboard"
D = ["yank_main_selection_to_clipboard", "delete_selection"]
V = "extend_to_line_end"

C-l = "goto_next_buffer"
C-h = "goto_previous_buffer"

esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
esc = ["collapse_selection", "normal_mode"]

[keys.select]
p = "replace_selections_with_clipboard"
P = "no_op"
y = "yank_joined_to_clipboard"
D = ["yank_main_selection_to_clipboard", "delete_selection"]
V = "extend_to_line_end"

esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
