[[language]]
name = "rust"
auto-format = true

[language.config]
checkOnSave = { command = "clippy" }

[language.config.check]
command = "clippy"

[[language]]
name = "bash"
auto-format = true
indent = { tab-width = 4, unit = "  " }
