[[language]]
name = "rust"
auto-format = true
# checkOnSave = { command = "clippy" }

[[language]]
name = "bash"
auto-format = true
indent = { tab-width = 4, unit = " " }

[[language]]
name = "nu"
auto-format = true
indent = { tab-width = 4, unit = " " }
