# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/ad493dc4-5a52-4061-9b0a-4fadaf6c9cf2";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6f20f78f-8a23-4f07-8726-67fa1da4c5b7".device = "/dev/disk/by-uuid/6f20f78f-8a23-4f07-8726-67fa1da4c5b7";

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/B578-83EA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/e0b1e797-4887-4e3c-a020-c7c506bcfa52"; }];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
